### ISSUE TITLE
`rug install` fails

### ISSUE THREAD

**Issue by gutierlf** [satellite-of-love/elm-rugs#2]
Hi! I can't wait to try elm-rugs. Looks really cool. Thanks in advance for looking into this issue!

I'm installing on a fairly new machine without lots of packages already installed. I had to install java (by the way, it might be good to insert that closer to the top of the README), and I'm at 1.8.0_144 (so I think this isn't the same issue as in #1). `rug install` fails with 

```
It looks as if you are missing required node modules.

Please make sure to run 'yarn install' or 'npm install' from within the .atomist folder to install all node module dependencies.
If this error persists, check that your 'package.json' lists all required dependencies.
```

I did the `npm install` in the `.atomist` folder, but the error persists.

Here's the stack trace from `rug install -X`:

```
.atomist/tests/project/UpgradeToBeginnerProgramSteps.ts(4,8): error TS2307: Cannot find module '@atomist/rug/test/project/Core'.
} from "@atomist/rug/test/project/Core";
       ^
        at com.atomist.rug.compiler.typescript.TypeScriptCompiler.compileFiles(TypeScriptCompiler.java:139)
	at com.atomist.rug.compiler.typescript.TypeScriptCompiler.compile(TypeScriptCompiler.java:66)
	at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.lambda$compile$0(AbstractCompilingAndOperationLoadingCommand.java:56)
	at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:22)
	at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.compile(AbstractCompilingAndOperationLoadingCommand.java:50)
	at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.run(AbstractCompilingAndOperationLoadingCommand.java:153)
	at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:17)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeReflectiveCommand(ReflectiveCommandRunner.java:93)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeCommand(ReflectiveCommandRunner.java:262)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:60)
	at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
	at com.atomist.rug.cli.Runner.run(Runner.java:40)
	at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
	at com.atomist.rug.cli.Main.main(Main.java:25)
```

**Comment by jessitron** [comment]
ooh thanks so much for reporting this! I wonder if some paths have changed in @atomist/rug since I published this. I'll look into it right away.

**Comment by gutierlf** [comment]
Awesome, thanks. After submitting this issue, I started wondering if I should have checked the rug library documentation itself, so I'm sort of glad to hear that it may actually be something in your control.

**Comment by jessitron** [comment]
resolved in 39bea0e42c730f11856b994de2d40e9a05df2bc7

@gutierlf pull and try again! I think what happened is `npm` changed, and no longer makes transitive dependencies available, so I made an explicit dependency.
