### ISSUE TITLE
java/sql/SQLException when running rug install

### ISSUE THREAD

**Issue by mbylstra** [satellite-of-love/elm-rugs#3]
Hi,
I'm getting this error when running rug install. It downloaded a whole lot of stuff, but then threw this error at the end. I get the same error if I run it again:

```
rug install -X
Resolving dependencies for jessitron:elm-rugs (2.0.5·local) completed

java.lang.NoClassDefFoundError: java/sql/SQLException
	at com.atomist.rug.cli.command.AbstractAnnotationBasedCommand.annotatedMethodWith(AbstractAnnotationBasedCommand.java:41)
	at com.atomist.rug.cli.command.AbstractAnnotationBasedCommand.validate(AbstractAnnotationBasedCommand.java:198)
	at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:17)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeReflectiveCommand(ReflectiveCommandRunner.java:93)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeCommand(ReflectiveCommandRunner.java:262)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:60)
	at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
	at com.atomist.rug.cli.Runner.run(Runner.java:40)
	at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
	at com.atomist.rug.cli.Main.main(Main.java:25)
Caused by: java.lang.ClassNotFoundException: java.sql.SQLException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.atomist.rug.cli.classloading.DelegatingUrlClassLoader.loadClass(DelegatingUrlClassLoader.java:46)
	... 15 more
```

```
java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

```
rug generate jessitron:elm-rugs:StaticPage happy-new-project-name -R
Resolving dependencies for jessitron:elm-rugs (latest·zip) failed

Configured repositories from ~/.atomist/cli.yml:
  central (http://repo.maven.apache.org/maven2/)
  rugs (https://atomist.jfrog.io/atomist/rugs)

Unable to resolve requested archive jessitron:elm-rugs (latest).
Please verify that specified archive exists in at least one of your configured repositories.
```
Let me know if there's any more info I can provide. Thanks!

**Comment by jessitron** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by jessitron** [comment]
The label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.



Possible duplicate or related issues are:

- #2: `rug install` fails
- #1: `rug install` step seems to fail to load compiled rug

**Comment by IvoNet** [comment]
I have the same problem:

```bash
Resolving dependencies for com.atomist:rug (1.0.0-m.5·jar) completed

java/sql/SQLException
```
